ARG BASE_IMAGE

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS dotnet

FROM ${BASE_IMAGE}

USER root

RUN apk add --no-cache \
    icu-libs \
    krb5-libs \
    libgcc \
    libstdc++ \
    zlib

COPY --from=dotnet /usr/share/dotnet /usr/share/dotnet

RUN ln -s /usr/share/dotnet/dotnet /usr/local/bin/dotnet

ENV DOTNET_ROOT=/usr/share/dotnet
ENV PATH="/usr/share/dotnet:${PATH}"
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV DOTNET_NOLOGO=1
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
ENV NUGET_XMLDOC_MODE=skip

USER opencode
